# Generated by Django 2.2.3 on 2019-07-03 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlannerApp', '0002_board_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamMembers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
