# Generated by Django 2.2.3 on 2019-07-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='items',
            field=models.ManyToManyField(to='PlannerApp.Item'),
        ),
    ]
