# Generated by Django 2.2.3 on 2019-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0007_project_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sprint',
            field=models.ManyToManyField(blank=True, null=True, to='PlannerApp.Sprint'),
        ),
    ]
