# Generated by Django 2.2.3 on 2019-07-24 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0012_auto_20190724_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 7, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2019, 7, 24)),
            preserve_default=False,
        ),
    ]
