# Generated by Django 2.2.3 on 2019-07-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0013_auto_20190724_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(),
        ),
    ]
