# Generated by Django 3.0.5 on 2020-05-01 09:12

import PlannerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0014_auto_20190724_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[(PlannerApp.models.Status['NEW'], 1), (PlannerApp.models.Status['GROOMED'], 2), (PlannerApp.models.Status['IN_PROGRESS'], 3), (PlannerApp.models.Status['IN_TESTING'], 4), (PlannerApp.models.Status['DONE'], 5), (PlannerApp.models.Status['REJECTED'], 6)], default=PlannerApp.models.Status['NEW'], max_length=5),
        ),
    ]
