# Generated by Django 3.0.5 on 2020-05-01 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlannerApp', '0021_auto_20200501_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamMembers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
