# Generated by Django 3.0.5 on 2020-05-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0022_auto_20200501_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlannerApp.Team'),
        ),
    ]
