# Generated by Django 3.0.5 on 2020-05-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0023_sprint_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlannerApp.Sprint'),
        ),
    ]
