# Generated by Django 3.0.5 on 2020-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0024_auto_20200501_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sprint',
        ),
        migrations.AddField(
            model_name='team',
            name='sprint',
            field=models.ManyToManyField(blank=True, null=True, to='PlannerApp.Sprint'),
        ),
    ]
