# Generated by Django 3.0.5 on 2020-05-04 12:46

import PlannerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0027_auto_20200501_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'NEW'), (2, 'GROOMED'), (3, 'IN_PROGRESS'), (4, 'IN_TESTING'), (5, 'DONE'), (6, 'REJECTED'), (7, 'DEPLOYED')], default=PlannerApp.models.Status['NEW']),
        ),
    ]
