# Generated by Django 3.0.5 on 2020-05-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0028_auto_20200504_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='sprints',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sprint',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
