# Generated by Django 3.0.6 on 2020-05-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0032_auto_20200524_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='wbs_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='wbs_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
