# Generated by Django 3.0.6 on 2020-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0033_auto_20200525_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
