# Generated by Django 3.0.6 on 2020-05-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0034_auto_20200525_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitem',
            old_name='progress',
            new_name='_progress',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='progress',
            new_name='_progress',
        ),
    ]
