# Generated by Django 3.0.5 on 2020-05-27 12:28

import PlannerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0035_auto_20200525_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN_PROGRESS'), (2, 'IN_TESTING'), (3, 'NEW'), (4, 'GROOMED'), (5, 'DONE'), (6, 'REJECTED'), (7, 'DEPLOYED')], default=PlannerApp.models.Status['NEW']),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN_PROGRESS'), (2, 'IN_TESTING'), (3, 'NEW'), (4, 'GROOMED'), (5, 'DONE'), (6, 'REJECTED'), (7, 'DEPLOYED')], default=PlannerApp.models.Status['NEW']),
        ),
    ]
