# Generated by Django 3.0.6 on 2020-06-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0036_auto_20200527_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='next_item',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='PlannerApp.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='next_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlannerApp.Item'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
