# Generated by Django 3.0.6 on 2020-06-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApp', '0037_auto_20200617_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='predecessor_item',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='PlannerApp.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='predecessor_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_predecessor_item', to='PlannerApp.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='next_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_next_item', to='PlannerApp.Item'),
        ),
    ]
